### ISSUE TITLE
1.0.0 Release Tracking

### ISSUE THREAD

**Issue by JacobJoergensen** [JacobJoergensen/PiperLang#24]
### Tasks

- [x] Add better docs
- [x] Add examples
- [x] Add more tests
- [x] Add status badge to readme.md
- [x] Add codecov coverage support
- [x] Add build artifacts
- [x] Add docker support
- [x] Add composer package support
- [x] Add packagist support
- [x] Cleanup .md files
